//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DejlienApp.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Menu {
            get {
                return ResourceManager.GetString("About_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string AccountSettings_Menu {
            get {
                return ResourceManager.GetString("AccountSettings_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander Island, Antarctic 
        ///
        ///.
        /// </summary>
        public static string Adress1_Contact {
            get {
                return ResourceManager.GetString("Adress1_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tellus, Milky Way.
        /// </summary>
        public static string Adress2_Contact {
            get {
                return ResourceManager.GetString("Adress2_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to check me out!.
        /// </summary>
        public static string CMButton_Home {
            get {
                return ResourceManager.GetString("CMButton_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check me out!.
        /// </summary>
        public static string CMOButton_Search {
            get {
                return ResourceManager.GetString("CMOButton_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Menu {
            get {
                return ResourceManager.GetString("Contact_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts_Menu {
            get {
                return ResourceManager.GetString("Contacts_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dejlien spreading love!.
        /// </summary>
        public static string Footer_Home {
            get {
                return ResourceManager.GetString("Footer_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dejlien! The only existing dejting website where you can find your intergalactic soulmate..
        /// </summary>
        public static string h3_About {
            get {
                return ResourceManager.GetString("h3_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Menu {
            get {
                return ResourceManager.GetString("Login_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff_LoginPartial {
            get {
                return ResourceManager.GetString("LogOff_LoginPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing:.
        /// </summary>
        public static string Marketing_Contact {
            get {
                return ResourceManager.GetString("Marketing_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be a part of this community, the only thing you need to do is to create an account. Then you will have full access to meet any other registered species! All the way from Milky Way to Tadpole Galaxy..
        /// </summary>
        public static string p_About {
            get {
                return ResourceManager.GetString("p_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or thoughts, please contact us on the support e-mail..
        /// </summary>
        public static string p_Contact {
            get {
                return ResourceManager.GetString("p_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find love, have you written anything in the searchbox?.
        /// </summary>
        public static string p_Search {
            get {
                return ResourceManager.GetString("p_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Menu {
            get {
                return ResourceManager.GetString("Register_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string RMButton_Home {
            get {
                return ResourceManager.GetString("RMButton_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_LoginPartial {
            get {
                return ResourceManager.GetString("Search_LoginPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We belive in long-distance love!.
        /// </summary>
        public static string Slogan_Home {
            get {
                return ResourceManager.GetString("Slogan_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Title_Contact {
            get {
                return ResourceManager.GetString("Title_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile information.
        /// </summary>
        public static string Title_ModifyProfile {
            get {
                return ResourceManager.GetString("Title_ModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Title_Search {
            get {
                return ResourceManager.GetString("Title_Search", resourceCulture);
            }
        }
    }
}
